return {
  version = "1.0.0",

  -- v0.2.1-compatible API
  create = require("ebe.ebe").create,
  LegacyEvent = require("ebe.core.event"),
  LegacyEventBus = require("ebe.core.event_bus"),
  ManualClock = require("ebe.core.clock"),
  StateStore = require("ebe.core.state_store"),
  RingBuffer = require("ebe.core.ring_buffer"),
  SpatialGrid = require("ebe.core.spatial_grid"),
  MemoryStore = require("ebe.memory.memory_store"),
  KnowledgeStore = require("ebe.perception.knowledge_store"),
  ObservationSystem = require("ebe.perception.observation_system"),
  ObserverRegistry = require("ebe.perception.observer_registry"),
  LegacyInterpreter = require("ebe.interpretation.interpreter"),
  PropagationSystem = require("ebe.propagation.propagation_system"),
  ReactionSystem = require("ebe.reaction.reaction_system"),

  -- v0.3.0 information-locality API
  Runtime = require("ebe.runtime"),
  Event = require("ebe.event"),
  EventBus = require("ebe.event_bus"),
  Observation = require("ebe.cognition.observation"),
  Memory = require("ebe.cognition.memory"),
  Belief = require("ebe.cognition.belief"),
  Knowledge = require("ebe.cognition.knowledge"),
  Interpretation = require("ebe.cognition.interpretation"),
  Propagation = require("ebe.social.propagation"),
  Reaction = require("ebe.social.reaction"),
  ActionRequest = require("ebe.action.action_request"),
  ActionGateway = require("ebe.action.action_gateway"),
  SourceLineage = require("ebe.social.source_lineage"),
  Institution = require("ebe.social.institution"),
  InstitutionalPolicy = require("ebe.social.institution_policy"),
  InformationEcology = require("ebe.social.information_ecology"),
  Collective = require("ebe.social.collective"),
  PixelGenV080 = require("ebe.integrations.pixelgen_v080"),
  PixelGenNetworkSynth = require("ebe.integrations.pixelgen_network_synth"),
  Snapshot = require("ebe.persistence.snapshot"),
  Json = require("ebe.persistence.json"),
  PersistenceContract = require("ebe.persistence.contract"),
  PublicContract = require("ebe.public_contract"),
}
