'use strict';
const A=require('assert'),fs=require('fs'),path=require('path'),F=require('../web/fpe');
const root=path.resolve(__dirname,'..');
const p=JSON.parse(fs.readFileSync(path.join(root,'data/projections/canonical_initial.json')));
const q=JSON.parse(fs.readFileSync(path.join(root,'data/projections/canonical_after.json')));
const r=F.create(p),cid=p.clusters[0].id,bid=p.clusters[0].buds[0].id;
const error=(fn,code)=>A.throws(fn,e=>e instanceof F.FPEError&&e.code===code);
const before=r.getProjection(),view=r.getView();
const req=r.request('inspect',cid,{mode:'deep',flags:['quiet'],weight:0.5});
A.equal(req.schema,'fpe.action_request/0.10.0');
A.equal(req.action,'inspect');A.deepStrictEqual(req.target,{kind:'cluster',id:cid});
A.equal(req.source.state_revision,p.source.state_revision);A.equal(req.source.state_tick,p.source.state_tick);
A.deepStrictEqual(r.getProjection(),before);A.deepStrictEqual(r.getView(),view);
req.payload.flags.push('mutated');req.source.dimensions[0]=999;
A.deepStrictEqual(r.request('inspect',cid,{mode:'deep',flags:['quiet'],weight:0.5}).payload.flags,['quiet']);
A.equal(r.request('inspect',bid).target.kind,'bud');
error(()=>r.request('',cid),'INVALID_REQUEST');error(()=>r.request('x'.repeat(65),cid),'INVALID_REQUEST');
error(()=>r.request('inspect','missing'),'UNKNOWN_ID');error(()=>r.request('inspect',cid,[]),'INVALID_REQUEST');
error(()=>r.request('inspect',cid,{bad:NaN}),'INVALID_REQUEST');error(()=>r.request('inspect',cid,{bad:Infinity}),'INVALID_REQUEST');
error(()=>r.request('inspect',cid,{bad:undefined}),'INVALID_REQUEST');
const cyclic={};cyclic.self=cyclic;error(()=>r.request('inspect',cid,cyclic),'INVALID_REQUEST');
error(()=>r.request('inspect',cid,{when:new Date()}),'INVALID_REQUEST');
const accessor={};Object.defineProperty(accessor,'x',{enumerable:true,get(){return 1;}});error(()=>r.request('inspect',cid,accessor),'INVALID_REQUEST');
const hidden={x:1};Object.defineProperty(hidden,'secret',{value:2,enumerable:false});error(()=>r.request('inspect',cid,hidden),'INVALID_REQUEST');
const symbolic={x:1};symbolic[Symbol('secret')]=2;error(()=>r.request('inspect',cid,symbolic),'INVALID_REQUEST');
const weirdArray=[1,2];weirdArray.extra=3;error(()=>r.request('inspect',cid,{items:weirdArray}),'INVALID_REQUEST');
const sparse=[];sparse.length=2;sparse[1]=1;error(()=>r.request('inspect',cid,{items:sparse}),'INVALID_REQUEST');
let deep={};let cursor=deep;for(let i=0;i<34;i++){cursor.next={};cursor=cursor.next;}error(()=>r.request('inspect',cid,deep),'INVALID_REQUEST');
A.deepStrictEqual(r.accept(q),{changed:true,revision:3});
const fresh=r.request('inspect',cid);A.equal(fresh.source.state_revision,3);A.equal(fresh.source.state_tick,q.source.state_tick);
console.log('action request PASS: envelope, target typing, JSON validation, isolation, no writeback, revision binding');
